version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urparts_scraper
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  scraper:
    build: ./scraper
    volumes:
      - ./scraper/:/scraper
    links:
      - db
  api:
    container_name: api
    ports:
      - "5000:5000"
    build: ./api

